# Generated by Django 5.0.1 on 2024-01-12 03:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kind', models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_region', models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
                ('img', models.ImageField(upload_to='pokemon/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'], message='Formato no permitido, solo admite archivos png, jpg, jpeg')])),
                ('id_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.kind')),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.region')),
            ],
        ),
    ]
