# Generated by Django 5.0.1 on 2024-01-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='id_kind',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='id_kind',
            field=models.ManyToManyField(to='pokemon.kind'),
        ),
    ]
