# Generated by Django 5.0.1 on 2024-01-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_remove_pokemon_id_kind_pokemon_id_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='name_kind',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_region',
            field=models.CharField(max_length=75),
        ),
    ]
